name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them. '
inputs:
  catching:
    description: 'Whether to Cache dependencies or not . '
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.catching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' && inputs.catching != 'true'
      run: npm ci
      shell: bash
